id_label: "CDCNo"
criteria_path: "https://raw.githubusercontent.com/redoio/resentencing_data_initiative/main/eligibility_model/code/offense_classification/county/los_angeles/selection_criteria.xlsx"
# Hashed input
base_path: "https://raw.githubusercontent.com/redoio/offenses_data/main/data"
dem_file_name: "demographics.xlsx"
curr_commits_file_name: "current_commitments.xlsx"
prior_commits_file_name: "prior_commitments.xlsx"
input_timestamp: 12_2023
eval_count: null
parallel: False
to_excel: True